Adds Compiler
GregBowyer/planout-golang pull request #7
Opened 2021-09-02 20:47 UTC by btamadio

Adds a compiler for turning PlanOut scripts into code that can be executed by the Interpreter.

See the README update for more details

2021-09-02 21:01 UTC, GregBowyer requested changes
It looks fine to me, I might rebase / squash the commits together.

Do the imports need to change?

2021-09-02 21:01 UTC, GregBowyer commented on compiler/ast/ast.go
> +	"github.com/stitchfix/planout-golang/compiler/token"
I would assume these need changing right?

2021-09-02 21:17 UTC, btamadio commented on compiler/ast/ast.go
> +	"github.com/stitchfix/planout-golang/compiler/token"
Just pushed the changes to rename the imports

2021-10-06 18:47 UTC, btamadio commented
Just following up on this - imports have been updated as requested! Would love to get this merged if possible!

2022-07-22 23:21 UTC, btamadio commented
> It looks fine to me, I might rebase / squash the commits together.
> 
> Do the imports need to change?

Imports have been updated. Any chance this could get merged?

2022-07-26 22:40 UTC, merged